services:
  vitales_db:
    image: mysql:8.0
    container_name: vitales_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: hospital_db
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      timeout: 5s
      interval: 5s
      retries: 10

  emqx:
    image: emqx/emqx:5.1.0
    container_name: vitales_broker
    environment:
      - EMQX_NODE__COOKIE=vitales_secret_cookie
    ports:
      - "1883:1883"
      - "18083:18083"
      - "8083:8083"
    restart: always
    healthcheck:
      test: ["CMD", "emqx", "ping"]
      timeout: 5s
      interval: 5s
      retries: 10

  backend:
    build: ./Backend
    container_name: vitales_backend
    environment:
      - DB_HOST=vitales_db
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=hospital_db
      - DB_PORT=3306
      - MQTT_BROKER=emqx
      - MQTT_PORT=1883
      - MQTT_TOPIC=esp32/temperatura
    depends_on:
      vitales_db:
        condition: service_healthy
      emqx:
        condition: service_healthy
    restart: always

  frontend:
    build: ./frontend
    container_name: vitales_frontend
    environment:
      - DB_HOST=vitales_db
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=hospital_db
      - DB_PORT=3306
    ports:
      - "8501:8501"
    depends_on:
      vitales_db:
        condition: service_healthy
    restart: always
